# # A ConfigMap is an object used to store Environment variables, Configuration files, Command-line arguments as key–value pairs.
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: frontend
#   namespace: roboshop
#   labels:
#     project: roboshop
#     tier: frontend
#     component: frontend
# data:
#   nginx.conf: |
#     user nginx;
#     worker_processes auto;
#     error_log /var/log/nginx/error.log notice;
#     pid /run/nginx.pid;

#     include /usr/share/nginx/modules/*.conf;

#     events {
#         worker_connections 1024;
#     }

#     http {
#         log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
#                           '$status $body_bytes_sent "$http_referer" '
#                           '"$http_user_agent" "$http_x_forwarded_for"';

#         access_log  /var/log/nginx/access.log  main;

#         sendfile            on;
#         tcp_nopush          on;
#         keepalive_timeout   65;
#         types_hash_max_size 4096;

#         include             /etc/nginx/mime.types;
#         default_type        application/octet-stream;

#         include /etc/nginx/conf.d/*.conf;

#         server {
#             listen       80;
#             listen       [::]:80;
#             server_name  _;
#             root         /usr/share/nginx/html;

#             include /etc/nginx/default.d/*.conf;

#             error_page 404 /404.html;
#             location = /404.html {
#             }

#             error_page 500 502 503 504 /50x.html;
#             location = /50x.html {
#             }

#             location /images/ {
#               expires 5s;
#               root   /usr/share/nginx/html;
#               try_files $uri /images/placeholder.jpg;
#             }
#             location /api/catalogue/ { proxy_pass http://catalogue:8080/; }
#             location /api/user/ { proxy_pass http://user:8080/; }
#             location /api/cart/ { proxy_pass http://cart:8080/; }
#             location /api/shipping/ { proxy_pass http://shipping:8080/; }
#             location /api/payment/ { proxy_pass http://payment:8080/; }

#             location /health {
#               stub_status on;
#               access_log off;
#             }

#         }
#     }
# ---
# Create multiple replicas of your pod. Always runs desired number of pods. 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: roboshop
  # These labels are replicaset labels reference
  labels:
    project: roboshop
    tier: frontend
    component: frontend
spec:
  replicas: 1
  selector:
  # Using these labels, replicaset selects the pod.
    matchLabels:
      project: roboshop
      tier: frontend
      component: frontend
  # This is Pod definition, Pod is subset of replicaset
  template:
    metadata:
      labels:
        project: roboshop
        tier: frontend
        component: frontend
    spec:
      # volumes:
      # - name: nginx-config
      #   configMap:
      #     name: frontend
      containers:
      - name: frontend
        image: javeedmohd214/frontend:1.4.0
        imagePullPolicy: Always       # Safe to pull everytime, there may be same version rebuilt and pushed.
        resources:
          # Soft limit
          requests:
            memory: "128Mi"
            cpu: "100m"
          # Hard limit
          limits:
            memory: "128Mi"
            cpu: "100m"
        # A readiness probe checks whether a container is ready to accept traffic. If it fails, K8s stops sending requests to that container.
        readinessProbe:
          # httpGet:
          #   path: /
          #   port: 80
          # To check whether the port is open/not
          tcpSocket:
            port: 80
          failureThreshold: 2
          periodSeconds: 10
          initialDelaySeconds: 15       # Container will become available in 35 seconds.
        # A liveness probe checks whether a container is still running properly. If it fails, K8s restarts the container.
        livenessProbe:
          httpGet:
            path: /
            port: 80
          failureThreshold: 2
          periodSeconds: 10
        # volumeMounts:
        # - name: nginx-config
        #   # By default it mounts and thinks as directory
        #   mountPath: "/etc/nginx/nginx.conf"
        #   subPath: nginx.conf
        #   readOnly: true
---
# By default, it will be cluster ip.
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: roboshop
  labels:
    project: roboshop
    tier: frontend
    component: frontend
spec:
  # We will be exposing the application externally to internet using LoadBalancer.
  type: LoadBalancer
  selector:
    # Labels are used as selectors.
    project: roboshop
    tier: frontend
    component: frontend
  ports:
  - protocol: TCP
    port: 80            # Service Port
    targetPort: 80      # Container Port   