# Create multiple replicas of your pod. Always runs desired number of pods. 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  # These labels are replicset labels reference
  labels:
    project: roboshop
    tier: database
    component: mysql
spec:
  replicas: 1
  selector:
  # Using these labels, replicaset selects the pod.
    matchLabels:
      project: roboshop
      tier: database
      component: mysql
  # This is Pod definition, Pod is subset of replicaset
  template:
    metadata:
      labels:
        project: roboshop
        tier: database
        component: mysql
    spec:
      containers:
      - name: mysql
        image: javeedmohd214/mysql:1.0.0
---
# By default, it will be cluster ip.
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    tier: database
    component: mysql
spec:
  selector:
    # Labels are used as selectors.
    project: roboshop
    tier: database
    component: mysql
  ports:
  - protocol: TCP
    port: 3306          # Service Port
    targetPort: 3306    # Container Port   