# A ConfigMap is an object used to store Environment variables, Configuration files, Command-line arguments as key–value pairs.
apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: catalogue
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"
---
# Create multiple replicas of your pod. Always runs desired number of pods. 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  # These labels are replicset labels reference
  labels:
    project: roboshop
    tier: backend
    component: catalogue
spec:
  replicas: 1
  selector:
  # Using these labels, replicaset selects the pod.
    matchLabels:
      project: roboshop
      tier: backend
      component: catalogue
  # This is Pod definition, Pod is subset of replicaset
  template:
    metadata:
      labels:
        project: roboshop
        tier: backend
        component: catalogue
    spec:
      containers:
      - name: catalogue
        image: javeedmohd214/catalogue:1.0.0
        resources:
          # Soft limit
          requests:
            memory: "128Mi"
            cpu: "100m"
          # Hard limit
          limits:
            memory: "128Mi"
            cpu: "100m"
        # A readiness probe checks whether a container is ready to accept traffic. If it fails, K8s stops sending requests to that container.
        readinessProbe:
          # httpGet:
          #   path: /health
          #   port: 8080
          # To check whether the port is open/not
          tcpSocket:
            port: 8080
          failureThreshold: 2
          periodSeconds: 10
          initialDelaySeconds: 15
        # A liveness probe checks whether a container is still running properly. If it fails, K8s restarts the container.
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 2
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: catalogue
---
# By default, it will be Cluster IP.
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: catalogue
spec:
  selector:
    # Labels are used as selectors.
    project: roboshop
    tier: backend
    component: catalogue
  ports:
  - protocol: TCP
    port: 8080           # Service Port
    targetPort: 8080     # Container Port   