# Create multiple replicas of your pod. Always runs desired number of pods. 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: roboshop
  # These labels are replicaset labels reference
  labels:
    project: roboshop
    tier: database
    component: redis
spec:
  replicas: 1
  selector:
  # Using these labels, replicaset selects the pod.
    matchLabels:
      project: roboshop
      tier: database
      component: redis
  # This is Pod definition, Pod is subset of replicaset
  template:
    metadata:
      labels:
        project: roboshop
        tier: database
        component: redis
    spec:
      containers:
      - name: redis
        image: redis:7.0
---
# By default, it will be cluster ip.
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
  labels:
    project: roboshop
    tier: database
    component: redis
spec:
  selector:
    # Labels are used as selectors.
    project: roboshop
    tier: database
    component: redis
  ports:
  - protocol: TCP
    port: 6379          # Service Port
    targetPort: 6379    # Container Port   